### PR TITLE
Add inspec tests and command, global resources

### PR DESCRIPTION
**Pull request by damacus**
- Fix template to look at the nodenv cookbook rather than the wrapper cookbook (default)

- Add a test cookbook with inspec tests
- Remove Vagrantfile we no longer require
- Remove default delivery and add  the community cookbook toml
- Remove git_url we're no longer using
- Remove default attributes.
- Remove the default recipe as we're a library cookbook and we now have a test cookbook
- Add root_path helper as we keep trying to find the root path for commands
- Grab the rbenv_script and make a nodenv_command resource so we can get the global version easily.
- Add inspec tests for global version setting

### CODE REVIEW

**Comment by damacus** [comment]
Hi!

What're the chances of this getting merged in soon?

**Comment by afaundez** [comment]
@damacus sorry, I had seen this for a while. Thanks for removing all the unnecessary stuff, mostly autogenerated.

I only have one doubt, regarding the Vagrantfile. I use it as a development environment. I don't know if it is a common/good practice, but it allows me to run and re-run the recipe in a clean enviroment whenever I need to. Do you know another way to use the recipe while you are developing?

**Comment by damacus** [comment]
usually the "standard" way to do this is with test kitchen and chefdk,
which under the hood generates a Vagrantfile (or another cloud platform
should someone configure that)

For example the HAProxy .kitchen.dokken.yml file configures the dokken
provider so that we can run it in Travis easily.

https://github.com/sous-chefs/haproxy/blob/master/.kitchen.dokken.yml

Hope that helps!
Dan

**Comment by afaundez** [comment]
Thanks for the pointer, [this](https://gist.github.com/smford22/f00f46471047422bd8a7#a-first-cookbook) worked, just adding attributes to `.kitchen.yml`.

**Pull request merged**
